apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "bridge-network1",
    "type": "bridge",
    "bridge": "br1",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.1.0/24",
      "network_name": "bridge-network1",
      "enable_overlapping_range": false
    }
  }'
