apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-config-worker-1
  namespace: networking
data:
  frr.conf: |
    hostname evpn-worker-1
    router bgp 65001
     bgp router-id 10.5.0.3
     bgp log-neighbor-changes
     bgp default l2vpn-evpn
     no bgp ebgp-requires-policy
     neighbor 10.5.0.2 remote-as 65000
     address-family ipv4 unicast
      redistribute connected
     exit-address-family
     !
     address-family l2vpn evpn
      neighbor 10.5.0.2 activate
      advertise-all-vni
     exit-address-family
    exit
    !
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-evpn-worker-1
  namespace: networking
  labels:
    app: ubuntu-evpn-worker-1
spec:
  selector:
    matchLabels:
      app: ubuntu-evpn-worker-1
  template:
    metadata:
      labels:
        app: ubuntu-evpn-worker-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: "talos-default-worker-1"
      volumes:
        - name: frr-config
          configMap:
            name: frr-config-worker-1
      containers:
        - name: ubuntu
          image: ubuntu
          volumeMounts:
            - name: frr-config
              mountPath: /root/frr.conf
              subPath: frr.conf
          command:
            - "/bin/bash"
            - "-c"
            - |
              apt-get update
              apt-get install -y iproute2 frr iputils-ping bridge-utils
              echo "Network tools and FRR installed."

              # Enable FRR daemons
              sed -i 's/^bgpd=no/bgpd=yes/' /etc/frr/daemons
              sed -i 's/^ospfd=no/ospfd=yes/' /etc/frr/daemons
              sed -i 's/^zebra=no/zebra=yes/' /etc/frr/daemons
              cp /root/frr.conf /etc/frr/frr.conf
              # Start FRR service
              echo "Starting FRR..."
              /usr/lib/frr/frrinit.sh start

              # Verify FRR is running
              sleep 5
              /usr/lib/frr/frrinit.sh status

              echo "FRR started successfully. Container will sleep now..."
              ip link add vxlan300 type vxlan id 300 local 10.5.0.3 dstport 4789 nolearning
              brctl addbr br300
              brctl addif br300 vxlan300
              brctl stp br300 off
              ip link set up dev br300
              ip link set up dev vxlan300
              sleep infinity
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
            runAsUser: 0
      restartPolicy: Always
      hostIPC: true
      hostNetwork: true
      hostPID: true
