apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm6
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm6
      annotations:
        k8s.v1.cni.cncf.io/networks: bridge-network300
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: bridge-iface
              bridge: {}
        resources:
          requests:
            memory: 1024M
            cpu: "1"
      networks:
        - name: default
          pod: {}
        - name: bridge-iface
          multus:
            networkName: bridge-network300
      volumes:
        - name: containerdisk
          containerDisk:
            image: mcas/kubevirt-ubuntu-20.04:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
