apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm3
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm3
      annotations:
        k8s.v1.cni.cncf.io/networks: bridge-network1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kubevirt.io/vm
                    operator: In
                    values:
                      - vm1
              topologyKey: kubernetes.io/hostname
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: bridge-iface
              bridge: {}
        resources:
          requests:
            memory: 1024M
            cpu: "1"
      networks:
        - name: default
          pod: {}
        - name: bridge-iface
          multus:
            networkName: bridge-network1
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
              write_files:
              - path: /etc/network/interfaces.d/eth1.cfg
                content: |
                  auto eth1
                  iface eth1 inet static
                  address 192.168.1.2
                  netmask 255.255.255.0
              runcmd:
              - ifup eth1
