apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network14
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "bridge-network14",
    "type": "bridge",
    "bridge": "br14",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.14.0/24",
      "network_name": "bridge-network14",
      "enable_overlapping_range": false
    }
  }'