apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network15
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "bridge-network15",
    "type": "bridge",
    "bridge": "br15",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.15.0/24",
      "network_name": "bridge-network15",
      "enable_overlapping_range": false
    }
  }'